Models/Role/RoleCreateModel.cs
namespace Ecommerce.Models;



public class RoleCreateModel
{
    public string Name { get; set; } = null!;
}

Models/Role/RoleEditModel.cs
namespace Ecommerce.Models;



public class RoleEditModel
{
    public string Name { get; set; } = null!;
}

Controllers/RoleController.cs
using System.Threading.Tasks;
using Ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

public class RoleController : Controller
{
    private readonly RoleManager<AppRole> _roleManager;

    public RoleController(RoleManager<AppRole> roleManager)
    {
        _roleManager = roleManager;
    }

    public ActionResult Index()
    {
        var roles = _roleManager.Roles.AsQueryable();
        return View(roles);
    }

    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(RoleCreateModel model)
    {
        if (ModelState.IsValid)
        {
            var role = new AppRole
            {
                Name = model.Name
            };

            var result = await _roleManager.CreateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var err in result.Errors)
            {
                ModelState.AddModelError("", err.Description);
            }

        }
        return View(model);
    }
}

Views/Role/Create.cshtml
@model RoleCreateModel
@{
    Layout = "_AdminLayout";
}

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-9">
            <div class="card shadow">
                <div class="card-header py-1 d-flex justify-content-between align-items-center">
                    <h5 class="card-title">Role Ekle</h5>
                    <a asp-controller="Role" asp-action="Index" class="btn btn-sm btn-primary">
                        <i class="fa-solid fa-list"></i>
                    </a>
                </div>
                <div class="card-body">
                    <div asp-validation-summary="All"></div>
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>

Views/Role/Index.cshtml
@model IQueryable<AppRole>

@{
    Layout = "_AdminLayout";
}


<div class="row">
    <div class="col">
        <div class="card shadow">
            <div class="card-header py-1 d-flex justify-content-between align-items-center">
                <h5 class="card-title">Roleler</h5>
                <a asp-controller="Role" asp-action="Create" class="btn btn-sm btn-primary">
                    <i class="fa-solid fa-plus"></i>
                </a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped mb-0">
                        <thead class="table-secondary">
                            <tr>
                                <th style="width: 20px;">Id</th>
                                <th>Role Adı</th>

                                <th style="width: 50px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var role in Model)
                            {
                                <tr>
                                    <td>@role.Id</td>
                                    <td>@role.Name</td>
                                    <td>
                                        <a asp-controller="Role" asp-action="Edit" asp-route-id="@role.Id"
                                            class="btn btn-primary btn-sm">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>